export interface DocumentTemplate {
  id: string
  type: string
  name: string
  description: string
  requiredTier: 'starter' | 'pro' | 'enterprise'
  icon: string
}

export const DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'capability-statement',
    type: 'capability_statement',
    name: 'Capability Statement',
    description: 'A professional 1-2 page overview of your company\'s core competencies, past performance, and differentiators.',
    requiredTier: 'starter',
    icon: '📋',
  },
  {
    id: 'letter-of-intent',
    type: 'letter_of_intent',
    name: 'Letter of Intent',
    description: 'Formal letter expressing interest in a specific government contract opportunity.',
    requiredTier: 'starter',
    icon: '✉️',
  },
  {
    id: 'past-performance',
    type: 'past_performance',
    name: 'Past Performance Summary',
    description: 'Structured summary of your relevant contract history, client satisfaction, and project outcomes.',
    requiredTier: 'starter',
    icon: '📊',
  },
  {
    id: 'rfi-response',
    type: 'rfi_response',
    name: 'RFI/Sources Sought Response',
    description: 'Professional response to Requests for Information and Sources Sought notices.',
    requiredTier: 'pro',
    icon: '🔍',
  },
  {
    id: 'teaming-agreement',
    type: 'teaming_agreement',
    name: 'Teaming Agreement Template',
    description: 'Standard teaming agreement for prime/subcontractor relationships on government proposals.',
    requiredTier: 'pro',
    icon: '🤝',
  },
]

export interface CompanyData {
  companyName: string
  uei?: string
  website?: string
  yearFounded?: number
  businessTypes: string[]
  naicsCodes: string[]
  certifications: string[]
  clearanceLevel?: string
  contactName?: string
  contactEmail?: string
  contactPhone?: string
}

export function generateCapabilityStatement(company: CompanyData): string {
  const businessTypeList = company.businessTypes.join(', ') || 'Small Business'
  const naicsList = company.naicsCodes.slice(0, 3).join(', ') || 'N/A'
  const certList = company.certifications.join(', ') || 'None'
  const founded = company.yearFounded ? `Founded in ${company.yearFounded}` : 'Established company'

  return `CAPABILITY STATEMENT
${company.companyName}
${'='.repeat(60)}

CORE COMPETENCIES
${company.companyName} provides world-class services and solutions to federal government clients. Our team of experts brings deep domain knowledge and proven methodologies to every engagement.

Core Service Areas:
• Program Management and Consulting
• Technical Services and Implementation
• Strategic Advisory and Analysis
• Quality Assurance and Compliance

DIFFERENTIATORS
• ${founded} with demonstrated government contracting experience
• Certified ${businessTypeList} enterprise
• Deep expertise in NAICS codes: ${naicsList}
• Agile delivery methodology with proven results
• Dedicated to mission success and client satisfaction

PAST PERFORMANCE
[Your company has successfully delivered on federal contracts across multiple agencies. Include specific examples of relevant past performance here.]

Project 1: [Agency Name] — [Brief description, value, period of performance]
Project 2: [Agency Name] — [Brief description, value, period of performance]
Project 3: [Agency Name] — [Brief description, value, period of performance]

COMPANY DATA
Legal Business Name: ${company.companyName}
UEI: ${company.uei || '[Your UEI Number]'}
CAGE Code: [Your CAGE Code]
Website: ${company.website || '[Your Website]'}
Business Type(s): ${businessTypeList}
Primary NAICS Codes: ${naicsList}
Certifications: ${certList}
${company.clearanceLevel ? `Security Clearance: ${company.clearanceLevel}` : ''}

CONTACT INFORMATION
${company.contactName || '[Contact Name]'}
${company.contactEmail || '[Email Address]'}
${company.contactPhone || '[Phone Number]'}
${company.website || '[Website]'}

${'='.repeat(60)}
Generated by IR — Government Contract Intelligence Platform
`
}

export function generateLetterOfIntent(company: CompanyData, contractTitle?: string, agency?: string): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const businessTypeList = company.businessTypes.join(', ') || 'Small Business'

  return `${today}

Contracting Officer
${agency || '[Agency Name]'}
[Address]
[City, State ZIP]

Re: Letter of Intent — ${contractTitle || '[Solicitation Title]'}
Solicitation Number: [Solicitation Number]

Dear Contracting Officer:

${company.companyName} hereby submits this Letter of Intent to respond to the above-referenced solicitation. We are highly qualified to provide the requested services and are committed to delivering exceptional value to ${agency || '[Agency Name]'}.

COMPANY OVERVIEW
${company.companyName} is a ${businessTypeList} organization with proven experience in federal contracting. ${company.yearFounded ? `Established in ${company.yearFounded}, we` : 'We'} have built a reputation for delivering high-quality solutions on time and within budget.

UEI: ${company.uei || '[Your UEI]'}
Primary NAICS: ${company.naicsCodes[0] || '[NAICS Code]'}
Certifications: ${company.certifications.join(', ') || 'None'}

RELEVANT QUALIFICATIONS
${company.companyName} brings the following qualifications to this opportunity:

1. Technical Expertise — Our team possesses direct experience relevant to the requirements outlined in this solicitation.

2. Past Performance — We have successfully performed similar work for federal government clients, demonstrating our ability to meet and exceed contract requirements.

3. Management Approach — We employ proven project management methodologies to ensure successful delivery.

4. Small Business Commitment — As a ${businessTypeList}, we are committed to bringing value-added solutions while supporting the government's small business goals.

We look forward to submitting a comprehensive proposal and welcome any questions regarding our qualifications.

Respectfully submitted,

[Authorized Signatory]
${company.companyName}
${company.contactEmail || '[Email]'}
${company.contactPhone || '[Phone]'}

${'='.repeat(60)}
Generated by IR — Government Contract Intelligence Platform
`
}

export function generatePastPerformanceSummary(company: CompanyData): string {
  return `PAST PERFORMANCE SUMMARY
${company.companyName}
${'='.repeat(60)}

OVERVIEW
This document summarizes ${company.companyName}'s relevant past performance demonstrating our ability to deliver high-quality services to federal government clients.

PERFORMANCE RECORD

CONTRACT 1
Agency: [Federal Agency Name]
Contract Number: [Contract Number]
Contract Value: $[Value]
Period of Performance: [Start Date] – [End Date]
NAICS Code: ${company.naicsCodes[0] || '[NAICS]'}
Type of Work: [Brief Description]

Performance: [Describe the work performed, challenges overcome, and outcomes achieved]

Customer Satisfaction: Excellent / Very Good / Satisfactory
Reference: [Name, Title, Phone, Email]

CONTRACT 2
Agency: [Federal Agency Name]
Contract Number: [Contract Number]
Contract Value: $[Value]
Period of Performance: [Start Date] – [End Date]
NAICS Code: ${company.naicsCodes[0] || '[NAICS]'}
Type of Work: [Brief Description]

Performance: [Describe the work performed, challenges overcome, and outcomes achieved]

Customer Satisfaction: Excellent / Very Good / Satisfactory
Reference: [Name, Title, Phone, Email]

CONTRACT 3
Agency: [Federal Agency Name]
Contract Number: [Contract Number]
Contract Value: $[Value]
Period of Performance: [Start Date] – [End Date]
NAICS Code: ${company.naicsCodes[0] || '[NAICS]'}
Type of Work: [Brief Description]

Performance: [Describe the work performed, challenges overcome, and outcomes achieved]

Customer Satisfaction: Excellent / Very Good / Satisfactory
Reference: [Name, Title, Phone, Email]

KEY METRICS
• On-time delivery rate: [X]%
• Within-budget completion: [X]%
• Customer satisfaction score: [X]/5
• Zero default / cure notices received

CERTIFICATIONS & QUALIFICATIONS
Business Type: ${company.businessTypes.join(', ') || 'Small Business'}
UEI: ${company.uei || '[UEI]'}
Certifications: ${company.certifications.join(', ') || 'None'}
${company.clearanceLevel ? `Security Clearance: ${company.clearanceLevel}` : ''}

${'='.repeat(60)}
Generated by IR — Government Contract Intelligence Platform
`
}

export function generateRFIResponse(company: CompanyData, rfiTitle?: string): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const businessTypeList = company.businessTypes.join(', ') || 'Small Business'

  return `${today}

Response to: ${rfiTitle || 'Request for Information / Sources Sought'}

Submitting Organization: ${company.companyName}
UEI: ${company.uei || '[Your UEI]'}
NAICS Codes: ${company.naicsCodes.join(', ') || '[NAICS Codes]'}
Business Type: ${businessTypeList}
Point of Contact: ${company.contactName || '[Name]'}, ${company.contactEmail || '[Email]'}

${'='.repeat(60)}

1. COMPANY BACKGROUND AND CAPABILITIES

${company.companyName} is a ${businessTypeList} ${company.yearFounded ? `founded in ${company.yearFounded}` : ''} with expertise in providing professional services to federal government agencies.

Relevant Capabilities:
• [Core capability 1 relevant to this RFI]
• [Core capability 2 relevant to this RFI]
• [Core capability 3 relevant to this RFI]
• [Core capability 4 relevant to this RFI]

2. TECHNICAL APPROACH

[Describe your technical approach to the requirements outlined in the RFI. Address each technical requirement specifically.]

Methodology: [Describe your methodology]
Tools and Technologies: [List relevant tools/technologies]
Quality Assurance: [Describe your QA approach]

3. RELEVANT EXPERIENCE

${company.companyName} has successfully performed similar work for federal clients:
• [Example 1: Agency, brief description, outcome]
• [Example 2: Agency, brief description, outcome]
• [Example 3: Agency, brief description, outcome]

4. TEAM QUALIFICATIONS

Key Personnel:
• [Name/Title] — [Brief qualifications]
• [Name/Title] — [Brief qualifications]
• [Name/Title] — [Brief qualifications]

Certifications: ${company.certifications.join(', ') || 'None'}
${company.clearanceLevel ? `Security Clearance Levels: ${company.clearanceLevel}` : ''}

5. RESPONSES TO SPECIFIC QUESTIONS

[Address each specific question or requirement from the RFI here]

Q1: [Question from RFI]
A1: [Your response]

Q2: [Question from RFI]
A2: [Your response]

6. SMALL BUSINESS INFORMATION

${company.companyName} is registered in SAM.gov as a ${businessTypeList}.
UEI: ${company.uei || '[UEI]'}
CAGE Code: [CAGE Code]
Primary NAICS: ${company.naicsCodes[0] || '[NAICS]'}

7. CONTACT INFORMATION

For questions regarding this response, please contact:

${company.contactName || '[Name]'}
${company.companyName}
${company.contactEmail || '[Email]'}
${company.contactPhone || '[Phone]'}
${company.website || '[Website]'}

${'='.repeat(60)}
Generated by IR — Government Contract Intelligence Platform
`
}

export function generateTeamingAgreement(company: CompanyData): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  return `TEAMING AGREEMENT

This Teaming Agreement ("Agreement") is entered into as of ${today}, between:

PARTY A (Prime Contractor):
Company Name: ${company.companyName}
UEI: ${company.uei || '[UEI]'}
Address: [Address]
("Prime")

AND

PARTY B (Subcontractor):
Company Name: [Subcontractor Company Name]
UEI: [Subcontractor UEI]
Address: [Address]
("Sub")

WHEREAS, the parties desire to team together to pursue the following government contract opportunity:

Solicitation: [Solicitation Title]
Solicitation Number: [Number]
Issuing Agency: [Agency]
Estimated Value: [Value]

NOW THEREFORE, the parties agree as follows:

1. PURPOSE
The purpose of this Agreement is to establish the terms under which Prime and Sub will cooperate to pursue, bid on, and perform the above-referenced contract.

2. PRIME/SUBCONTRACTOR RELATIONSHIP
(a) Prime shall serve as the prime contractor and shall be responsible for overall contract management and performance.
(b) Sub shall provide the following work scope: [Description of subcontractor's scope]
(c) Sub's estimated share of contract value: [X]%

3. PROPOSAL DEVELOPMENT
(a) Both parties shall contribute to proposal development as agreed.
(b) Prime shall have final authority over proposal content and submission.
(c) Each party bears its own proposal preparation costs.

4. EXCLUSIVITY
During the term of this Agreement, neither party shall team with other companies for this specific opportunity without written consent of the other party.

5. CONFIDENTIALITY
Both parties agree to maintain confidentiality of the other party's proprietary information shared during this teaming arrangement.

6. TERM
This Agreement shall remain in effect until: (a) award of the contract, (b) mutual written agreement to terminate, or (c) one year from the date hereof, whichever occurs first.

7. NO BINDING COMMITMENT
This Agreement does not obligate either party to award a subcontract. Subcontract award is contingent upon prime contract award and successful negotiations.

8. GOVERNING LAW
This Agreement shall be governed by the laws of [State].

SIGNATURES

PRIME CONTRACTOR:
${company.companyName}

By: ________________________________
Name: ${company.contactName || '[Authorized Representative]'}
Title: [Title]
Date: ________________

SUBCONTRACTOR:
[Subcontractor Company Name]

By: ________________________________
Name: [Name]
Title: [Title]
Date: ________________

${'='.repeat(60)}
Generated by IR — Government Contract Intelligence Platform
NOTE: This template is for informational purposes. Consult legal counsel before execution.
`
}

export function generateDocument(type: string, company: CompanyData, context?: { title?: string; agency?: string }): string {
  switch (type) {
    case 'capability_statement':
      return generateCapabilityStatement(company)
    case 'letter_of_intent':
      return generateLetterOfIntent(company, context?.title, context?.agency)
    case 'past_performance':
      return generatePastPerformanceSummary(company)
    case 'rfi_response':
      return generateRFIResponse(company, context?.title)
    case 'teaming_agreement':
      return generateTeamingAgreement(company)
    default:
      return 'Unknown document type'
  }
}
