// State directory — powers the /states programmatic SEO pages.
//
// Small businesses search geographically ("government contracts in Florida"),
// and place-of-performance is a real bidding consideration. Each entry pairs a
// live-contract filter with a genuine one-paragraph read on the state's
// federal footprint — the content that earns the ranking.
//
// Contract.placeOfPerformance is built as "City, ST" (lib/sam-api), so the
// state match is a token match on the two-letter code.

import type { Contract } from './sam-api'

export interface StateEntry {
  slug: string
  name: string
  code: string      // USPS two-letter
  footprint: string // one-paragraph federal-presence overview
}

export const STATES: StateEntry[] = [
  { slug: 'alabama', name: 'Alabama', code: 'AL', footprint: 'Huntsville is one of the densest federal-technology corridors in the country: Redstone Arsenal hosts Army aviation and missile commands plus NASA\'s Marshall Space Flight Center, with the FBI expanding its campus there. Anniston Army Depot anchors vehicle sustainment work, and Maxwell-Gunter AFB in Montgomery drives Air Force education and cyber programs.' },
  { slug: 'alaska', name: 'Alaska', code: 'AK', footprint: 'Joint Base Elmendorf-Richardson and Eielson AFB anchor Arctic defense spending, with F-35 beddown driving construction and support contracts. The Coast Guard, NOAA, and the Interior Department maintain large operations, and remote-logistics, fuel, and construction work carries premiums few Lower-48 firms compete for.' },
  { slug: 'arizona', name: 'Arizona', code: 'AZ', footprint: 'Fort Huachuca is the Army\'s intelligence and network-testing hub, Luke and Davis-Monthan AFBs drive aviation work, and Yuma Proving Ground tests equipment across a huge desert range. Border-security spending through DHS/CBP adds a steady non-defense pipeline.' },
  { slug: 'arkansas', name: 'Arkansas', code: 'AR', footprint: 'Little Rock AFB is the C-130 training center of the Air Force, and Pine Bluff Arsenal handles specialized chemical-biological defense production. USDA, VA, and Corps of Engineers civil-works spending rounds out a market where local past performance goes far.' },
  { slug: 'california', name: 'California', code: 'CA', footprint: 'The largest state federal market by dollars: Navy fleet concentration in San Diego, Edwards AFB and China Lake for flight test and weapons research, Vandenberg for space launch, plus massive VA, DHS, and GSA civilian spending. Competition is deep, but so is the sub-tier teaming ecosystem.' },
  { slug: 'colorado', name: 'Colorado', code: 'CO', footprint: 'Colorado Springs is the center of military space: Space Force bases (Peterson, Schriever, Cheyenne Mountain), NORAD/NORTHCOM, and the Air Force Academy. The Denver Federal Center hosts dozens of civilian agencies, and NOAA/NIST labs in Boulder buy research and technical services.' },
  { slug: 'connecticut', name: 'Connecticut', code: 'CT', footprint: 'Naval Submarine Base New London at Groton anchors undersea-warfare spending, with Electric Boat driving one of the largest defense-industrial supply chains in the Northeast — a rich subcontracting market for machining, engineering, and logistics firms.' },
  { slug: 'delaware', name: 'Delaware', code: 'DE', footprint: 'Dover AFB operates the military\'s largest aerial port and mortuary-affairs center, driving logistics, facility, and services contracts. Delaware\'s small size means less local competition for the federal work that does post.' },
  { slug: 'district-of-columbia', name: 'Washington, DC', code: 'DC', footprint: 'The seat of nearly every agency headquarters and the highest concentration of professional-services contracting on earth. IT modernization, advisory, staffing, and facility support dominate; GSA schedules and small-business set-asides are the standard entry points.' },
  { slug: 'florida', name: 'Florida', code: 'FL', footprint: 'A top-five federal market: MacDill AFB in Tampa hosts CENTCOM and SOCOM (a magnet for services and technology firms), Eglin AFB and the Panhandle ranges drive weapons test work, Navy aviation trains at Pensacola and Jacksonville, and Kennedy Space Center anchors the Space Coast. Add one of the largest VA populations in the country and Florida small businesses have federal buyers in every direction.' },
  { slug: 'georgia', name: 'Georgia', code: 'GA', footprint: 'Fort Eisenhower in Augusta is the Army\'s cyber center, Robins AFB sustains major Air Force weapon systems, and Forts Moore and Stewart anchor large troop populations. Atlanta hosts the CDC and major civilian federal offices — a diverse market across defense, health, and logistics.' },
  { slug: 'hawaii', name: 'Hawaii', code: 'HI', footprint: 'INDOPACOM headquarters and the Pearl Harbor Naval Shipyard make Hawaii the hub of Pacific-theater spending. Ship maintenance, base operations, construction, and logistics dominate, and the distance from mainland competitors favors firms with island presence.' },
  { slug: 'idaho', name: 'Idaho', code: 'ID', footprint: 'Idaho National Laboratory is the nation\'s lead nuclear-energy research site, buying engineering, environmental, security, and technical services at scale. Mountain Home AFB and large Interior/Forest Service land management add steady operational contracts.' },
  { slug: 'illinois', name: 'Illinois', code: 'IL', footprint: 'Scott AFB hosts USTRANSCOM — the command that buys transportation and logistics for the entire military. Rock Island Arsenal manufactures and manages Army materiel, and Naval Station Great Lakes trains every Navy recruit. Chicago adds major GSA, VA, and EPA civilian spending.' },
  { slug: 'indiana', name: 'Indiana', code: 'IN', footprint: 'Naval Support Activity Crane is one of the Navy\'s premier engineering and sustainment centers for electronics and expeditionary systems, feeding a strong technical-services and manufacturing supply chain across southern Indiana.' },
  { slug: 'iowa', name: 'Iowa', code: 'IA', footprint: 'The Iowa Army Ammunition Plant produces critical munitions, and USDA\'s large presence drives agricultural research and services spending. A less crowded market where responsive local firms build federal past performance faster.' },
  { slug: 'kansas', name: 'Kansas', code: 'KS', footprint: 'Forts Riley and Leavenworth anchor Army operations and education commands, and McConnell AFB flies the tanker fleet. Wichita\'s aviation-manufacturing base feeds defense subcontracting across airframes and components.' },
  { slug: 'kentucky', name: 'Kentucky', code: 'KY', footprint: 'Fort Knox and Fort Campbell are two of the Army\'s largest installations, driving base operations, construction, and services work. The Blue Grass Army Depot handles munitions, and Louisville hosts significant VA and Corps of Engineers activity.' },
  { slug: 'louisiana', name: 'Louisiana', code: 'LA', footprint: 'Fort Johnson trains brigades at the JRTC, Barksdale AFB hosts Air Force Global Strike Command, and NASA\'s Michoud facility in New Orleans builds space hardware. The Corps of Engineers spends heavily on flood control and coastal work — a natural fit for regional construction and environmental firms.' },
  { slug: 'maine', name: 'Maine', code: 'ME', footprint: 'Portsmouth Naval Shipyard overhauls nuclear submarines and Bath Iron Works builds destroyers, anchoring a shipbuilding supply chain that buys machining, electrical, and technical services across the state.' },
  { slug: 'maryland', name: 'Maryland', code: 'MD', footprint: 'Fort Meade hosts NSA and U.S. Cyber Command — the densest cybersecurity contracting market in the world. Aberdeen Proving Ground drives Army C5ISR and test work; NIH, FDA, NIST, and CMS make Maryland the center of federal health and standards spending. Cleared talent is the currency here.' },
  { slug: 'massachusetts', name: 'Massachusetts', code: 'MA', footprint: 'Hanscom AFB manages Air Force command-and-control acquisitions, the Army\'s Natick Soldier Systems Center develops everything a soldier wears or carries, and MIT Lincoln Laboratory anchors advanced R&D — a strong market for research and engineering firms.' },
  { slug: 'michigan', name: 'Michigan', code: 'MI', footprint: 'The Detroit Arsenal hosts Army ground-vehicle commands (TACOM/GVSC), making Michigan the center of military vehicle engineering and sustainment — a natural bridge for automotive-supply-chain firms entering defense. Selfridge ANGB and Corps of Engineers Great Lakes work add operational spending.' },
  { slug: 'minnesota', name: 'Minnesota', code: 'MN', footprint: 'A civilian-weighted market: large VA medical operations, USDA and Interior programs, and Corps of Engineers work on the Mississippi. Medical-device and manufacturing strength positions Minnesota firms well for DLA and VA supply contracts.' },
  { slug: 'mississippi', name: 'Mississippi', code: 'MS', footprint: 'Stennis Space Center tests every large NASA rocket engine and hosts Navy oceanography; Ingalls Shipbuilding in Pascagoula builds major surface combatants; Keesler AFB trains Air Force technical fields; and the Corps\' ERDC in Vicksburg is the military\'s premier engineering R&D lab.' },
  { slug: 'missouri', name: 'Missouri', code: 'MO', footprint: 'The NGA is building its next-generation western headquarters in St. Louis (a large geospatial-intelligence market), Fort Leonard Wood trains engineers and military police, Whiteman AFB flies the B-2, and the Kansas City National Security Campus manufactures for the nuclear enterprise.' },
  { slug: 'montana', name: 'Montana', code: 'MT', footprint: 'Malmstrom AFB operates ICBM fields — and the Sentinel missile-modernization program is bringing years of construction and support spending. Interior, Forest Service, and BLM land management add steady services work across the state.' },
  { slug: 'nebraska', name: 'Nebraska', code: 'NE', footprint: 'Offutt AFB hosts USSTRATCOM, driving command-and-control, IT, and facility spending. USDA and Corps of Engineers Missouri River work give civilian-side entry points in a market with limited local competition.' },
  { slug: 'nevada', name: 'Nevada', code: 'NV', footprint: 'Nellis and Creech AFBs anchor air-combat training and the RPA enterprise, and the Nevada National Security Site supports nuclear-stewardship missions with large security, environmental, and technical-services contracts. VA and Interior spending grows with the population.' },
  { slug: 'new-hampshire', name: 'New Hampshire', code: 'NH', footprint: 'Portsmouth Naval Shipyard (on the Maine border) drives skilled-trades and engineering demand, and the New Boston Space Force Station supports satellite operations. A compact market where shipyard-adjacent capability wins.' },
  { slug: 'new-jersey', name: 'New Jersey', code: 'NJ', footprint: 'Joint Base McGuire-Dix-Lakehurst is the East Coast\'s mobility hub, and Picatinny Arsenal is the Army\'s center for armaments and munitions engineering — strong demand for engineering services, manufacturing, and base support.' },
  { slug: 'new-mexico', name: 'New Mexico', code: 'NM', footprint: 'Sandia and Los Alamos national laboratories anchor nuclear-security R&D with enormous procurement budgets; Kirtland AFB hosts Air Force nuclear and space research; White Sands tests missiles; Holloman trains pilots. Per capita, one of the most federally dependent markets in the country.' },
  { slug: 'new-york', name: 'New York', code: 'NY', footprint: 'Fort Drum hosts the 10th Mountain Division, the Air Force Research Lab\'s information directorate in Rome drives cyber and C4I work, Watervliet Arsenal manufactures cannon, and downstate hosts huge VA, GSA, and DHS civilian operations.' },
  { slug: 'north-carolina', name: 'North Carolina', code: 'NC', footprint: 'Fort Liberty is the Army\'s largest installation and home of special-operations forces, Camp Lejeune and Cherry Point anchor Marine Corps operations, and Seymour Johnson flies Strike Eagles. Base operations, construction, logistics, and training services dominate a very large market.' },
  { slug: 'north-dakota', name: 'North Dakota', code: 'ND', footprint: 'Minot AFB operates both bombers and ICBMs (with Sentinel modernization coming), and Grand Forks AFB anchors unmanned and space-networking missions. Sparse local competition for steady federal work.' },
  { slug: 'ohio', name: 'Ohio', code: 'OH', footprint: 'Wright-Patterson AFB hosts Air Force Materiel Command, the Air Force Research Laboratory, and NASIC — one of the largest concentrations of defense acquisition and R&D anywhere. DFAS and DLA Land & Maritime in Columbus buy at national scale, and NASA Glenn in Cleveland adds aerospace research.' },
  { slug: 'oklahoma', name: 'Oklahoma', code: 'OK', footprint: 'Tinker AFB is the Air Force\'s largest sustainment center (engines and airframes), Fort Sill trains artillery and air defense, Altus trains mobility crews, and McAlester loads the military\'s bombs. Sustainment, MRO, and manufacturing capability wins here.' },
  { slug: 'oregon', name: 'Oregon', code: 'OR', footprint: 'A civilian-weighted market: Corps of Engineers hydropower and river work, large Forest Service and BLM programs, and VA medical operations. Wildfire-related contracting (aviation, logistics, services) has grown into a significant recurring market.' },
  { slug: 'pennsylvania', name: 'Pennsylvania', code: 'PA', footprint: 'Tobyhanna Army Depot is the military\'s premier electronics-maintenance facility, Letterkenny overhauls air-defense systems, DLA\'s Philadelphia operations buy clothing, medical, and subsistence at national scale, and the Navy\'s Philadelphia yard engineers ship systems. Strong for manufacturing and sustainment firms.' },
  { slug: 'rhode-island', name: 'Rhode Island', code: 'RI', footprint: 'The Naval Undersea Warfare Center in Newport designs and tests submarine combat systems, and the Naval War College anchors education programs — a concentrated, technical market for engineering and research services.' },
  { slug: 'south-carolina', name: 'South Carolina', code: 'SC', footprint: 'Joint Base Charleston moves cargo and hosts major Navy IT operations (NIWC Atlantic — a large IT contracting center), Shaw AFB hosts fighter wings and Army Central, Parris Island trains Marines, and the Savannah River Site runs multibillion-dollar environmental-management work.' },
  { slug: 'south-dakota', name: 'South Dakota', code: 'SD', footprint: 'Ellsworth AFB is the first beddown base for the B-21 bomber — driving a wave of construction, infrastructure, and support contracting through the decade. Interior and agriculture programs add civilian work.' },
  { slug: 'tennessee', name: 'Tennessee', code: 'TN', footprint: 'Oak Ridge hosts DOE\'s largest science and security campuses (ORNL, Y-12) with massive management and support procurement; Arnold AFB runs the nation\'s biggest flight-simulation test complex; and Millington processes Navy personnel. Milan and Holston plants produce munitions.' },
  { slug: 'texas', name: 'Texas', code: 'TX', footprint: 'The second-largest state federal market: Joint Base San Antonio (military medicine and cyber), Forts Cavazos and Bliss (two of the Army\'s biggest posts), Corpus Christi depot aviation, NASA Johnson in Houston, and enormous VA and DHS/CBP spending. Every capability has a buyer somewhere in Texas.' },
  { slug: 'utah', name: 'Utah', code: 'UT', footprint: 'Hill AFB sustains fighters and ICBMs (Sentinel program growth), the Utah Test and Training Range hosts weapons testing, Dugway Proving Ground tests chem-bio defense, and the IRS runs major processing operations in Ogden.' },
  { slug: 'vermont', name: 'Vermont', code: 'VT', footprint: 'A small but real market: Army and Air National Guard operations (including F-35 basing in Burlington), VA medical facilities, and border-related DHS work along the northern frontier.' },
  { slug: 'virginia', name: 'Virginia', code: 'VA', footprint: 'The epicenter of federal contracting: the Pentagon, Norfolk\'s naval concentration (the world\'s largest naval base), Quantico, Langley AFB, CIA and countless agency headquarters, plus the Northern Virginia professional-services corridor. More contract dollars flow here than anywhere — and more competitors chase them.' },
  { slug: 'washington', name: 'Washington', code: 'WA', footprint: 'Joint Base Lewis-McChord anchors Army and mobility operations, Puget Sound Naval Shipyard overhauls carriers and submarines, Naval Base Kitsap hosts strategic forces, and DOE\'s Hanford site runs some of the largest environmental-cleanup contracts in government.' },
  { slug: 'west-virginia', name: 'West Virginia', code: 'WV', footprint: 'The FBI\'s CJIS division in Clarksburg is the bureau\'s largest facility (major IT and support spending), NIOSH and other health agencies operate in Morgantown, and Treasury operations in Parkersburg process federal payments.' },
  { slug: 'wisconsin', name: 'Wisconsin', code: 'WI', footprint: 'Fort McCoy is a major mobilization and training site, and Wisconsin\'s heavy-manufacturing base (including major defense-vehicle production in Oshkosh) feeds large DoD supply chains — strong subcontracting territory for machining and components.' },
  { slug: 'wyoming', name: 'Wyoming', code: 'WY', footprint: 'F.E. Warren AFB operates ICBM fields entering Sentinel modernization — years of construction and support work ahead — and Interior/park operations (Yellowstone, Grand Teton) drive steady services and infrastructure contracting.' },
]

export function getState(slug: string): StateEntry | undefined {
  return STATES.find((s) => s.slug === slug)
}

// Place-of-performance is "City, ST" — match the two-letter token exactly so
// "VA" never matches "NEVADA" or a word inside the city name.
export function contractMatchesState(contract: Contract, entry: StateEntry): boolean {
  const pop = contract.placeOfPerformance || ''
  if (!pop) return false
  return pop.split(',').some((token) => token.trim().toUpperCase() === entry.code)
}
